/* ============================================================
   SHREEJI INFOTECH — Store Products Data Source
   ============================================================ */

export const STORE_PRODUCTS = [
    {
        id: 'ram-8gb-ddr4',
        name: '8GB RAM DDR 4',
        brand: 'Crucial / Kingston / Hynix',
        category: 'ram',
        price: 4500,
        originalPrice: 5500,
        image: '../assets/images/products/ram-ddr4.png',
        images: ['../assets/images/products/ram-ddr4.png'],
        rating: 4.8,
        reviews: 86,
        sku: 'RAM-8GB-DDR4',
        specs: { Capacity: '8GB', Speed: '3200MHz', Type: 'DDR4', Form: 'SODIMM / UDIMM' },
        description: 'High-speed 8GB DDR4 memory module for desktop and laptop performance upgrades. Features 3200MHz clock speed, low power consumption, and maximum system stability with 100% genuine brand warranty.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ram-16gb-ddr4',
        name: '16GB RAM DDR4',
        brand: 'Crucial / Kingston / Hynix',
        category: 'ram',
        price: 9500,
        originalPrice: 11500,
        image: '../assets/images/products/ram-ddr4.png',
        images: ['../assets/images/products/ram-ddr4.png'],
        rating: 4.9,
        reviews: 112,
        sku: 'RAM-16GB-DDR4',
        specs: { Capacity: '16GB', Speed: '3200MHz', Type: 'DDR4', Form: 'SODIMM / UDIMM' },
        description: 'Premium 16GB DDR4 RAM stick designed for smooth multitasking, content creation, and heavy workloads. Plug and play installation with full compatibility.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-128gb-sata',
        name: '128GB SSD SATA',
        brand: 'Crucial / Western Digital / Kingston',
        category: 'ssd',
        price: 3500,
        originalPrice: 4200,
        image: '../assets/images/products/ssd-sata.png',
        images: ['../assets/images/products/ssd-sata.png'],
        rating: 4.6,
        reviews: 94,
        sku: 'SSD-128GB-SATA',
        specs: { Capacity: '128GB', Interface: 'SATA III 6Gb/s', ReadSpeed: '550 MB/s', Form: '2.5 inch' },
        description: 'Ultra-reliable 128GB 2.5" SATA solid state drive. Upgrade your slow mechanical hard drive to experience up to 10x faster boot times and responsive application launches.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-256gb-sata',
        name: '256GB SSD SATA',
        brand: 'Crucial / Western Digital / Kingston',
        category: 'ssd',
        price: 4500,
        originalPrice: 5600,
        image: '../assets/images/products/ssd-sata.png',
        images: ['../assets/images/products/ssd-sata.png'],
        rating: 4.7,
        reviews: 148,
        sku: 'SSD-256GB-SATA',
        specs: { Capacity: '256GB', Interface: 'SATA III 6Gb/s', ReadSpeed: '550 MB/s', Form: '2.5 inch' },
        description: 'High performance 256GB SATA SSD drive. Essential storage upgrade for laptops and desktops providing fast boot speeds, quick file transfers, and durable shock resistance.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-512gb-sata',
        name: '512GB SSD SATA',
        brand: 'Crucial / Western Digital / Kingston',
        category: 'ssd',
        price: 7500,
        originalPrice: 9000,
        image: '../assets/images/products/ssd-sata.png',
        images: ['../assets/images/products/ssd-sata.png'],
        rating: 4.8,
        reviews: 176,
        sku: 'SSD-512GB-SATA',
        specs: { Capacity: '512GB', Interface: 'SATA III 6Gb/s', ReadSpeed: '560 MB/s', Form: '2.5 inch' },
        description: 'Spacious 512GB 2.5" SATA SSD for expanded high-speed storage. Perfect for operating systems, games, and large office applications with durable flash storage technology.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-128gb-nvme',
        name: '128GB SSD NVME',
        brand: 'Samsung / Crucial / Kingston',
        category: 'ssd',
        price: 3200,
        originalPrice: 4000,
        image: '../assets/images/products/ssd-nvme.png',
        images: ['../assets/images/products/ssd-nvme.png'],
        rating: 4.7,
        reviews: 82,
        sku: 'SSD-128GB-NVME',
        specs: { Capacity: '128GB', Interface: 'PCIe NVMe M.2 2280', ReadSpeed: '2100 MB/s', Form: 'M.2' },
        description: 'Next-gen M.2 128GB NVMe SSD offering blazing speeds up to 2,100 MB/s read speed. Direct motherboard installation for ultra-compact, cable-free high performance.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-256gb-nvme',
        name: '256GB SSD NVME',
        brand: 'Samsung / Crucial / Kingston',
        category: 'ssd',
        price: 5000,
        originalPrice: 6200,
        image: '../assets/images/products/ssd-nvme.png',
        images: ['../assets/images/products/ssd-nvme.png'],
        rating: 4.8,
        reviews: 154,
        sku: 'SSD-256GB-NVME',
        specs: { Capacity: '256GB', Interface: 'PCIe NVMe M.2 2280', ReadSpeed: '3200 MB/s', Form: 'M.2' },
        description: 'Ultra-fast 256GB PCIe NVMe M.2 SSD drive. Delivers read speeds up to 3,200 MB/s for instantaneous OS booting, quick rendering, and seamless multitasking.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    },
    {
        id: 'ssd-512gb-nvme',
        name: '512GB SSD NVME',
        brand: 'Samsung / Crucial / Kingston',
        category: 'ssd',
        price: 8100,
        originalPrice: 9800,
        image: '../assets/images/products/ssd-nvme.png',
        images: ['../assets/images/products/ssd-nvme.png'],
        rating: 4.9,
        reviews: 210,
        sku: 'SSD-512GB-NVME',
        specs: { Capacity: '512GB', Interface: 'PCIe NVMe M.2 2280', ReadSpeed: '3500 MB/s', Form: 'M.2' },
        description: 'Top-tier 512GB NVMe M.2 solid state drive. Engineered for high performance computing, intensive video editing, and gaming with speeds up to 3,500 MB/s.',
        inStock: true,
        gstRate: 18,
        warranty: '3 Years Warranty'
    }
];
